### ISSUE TITLE
Are the available datasets whole exome sequencing data ?

### ISSUE THREAD

**Issue by kb472** [PoisonAlien/TCGAmutations#1]
Hello,
I am very interested in comparing my data with the TCGA mutations. My data (mutations in RNA-seq data)is in VCF file format  which I converted  to MAF files.  I wanted to check with if you if the available datasets in your package are from whole exome sequencing data ? Do you have any datasets that are mutations from TGGA RNA-seq cohorts ? 
Thanks, K

**Comment by PoisonAlien** [comment]
Hello,

All samples are from TCGA WXS cohort. None of the RNA-Seq samples were used for this.
