### ISSUE TITLE
Significant number of discrepancies for LUAD clinical data -  vital_status / days_to_death / or days_to_last_followup

### ISSUE THREAD

**Issue by mitchellcheung8** [PoisonAlien/TCGAmutations#17]
I was using TCGAmutations to obtain LUAD mutation and clinical data from 'TCGA MC3', so I can plot survival data (Kaplan–Meier) using the mafsurvival function of the maftools library.

I noticed differences between the mafsurvival generated graph (LUAD for the CDKN2A gene) with the survival graph generated on-line (https://www.tcga-survival.com/data-table?view=gene&gene=CDKN2A&filter=cancer_type&cancer_type=LUAD).

To determine the cause of this, I then downloaded the mc3 MAF and the clinical data from "https://gdc.cancer.gov/node/905/":
1)  mc3.v0.2.8.PUBLIC.maf
2)  clinical_PANCAN_patient_with_followup.tsv
I then processed the files with maftools after subsetting for LUAD samples.
When I performed 'mafsurvival' for the CDKN2A gene with this data, it was identical to the www.tcga-survival.com website.

To determine the discrepancies, I compared the specific clinical data downloaded by TCGAmutations and the ones downloaded from "https://gdc.cancer.gov/node/905/".

Here are a few examples of the inaccurate info I found from the pre-compiled TCGAmutations clinical data:
TCGA-44-5645-01A-51D-A27T-08 ,       days to last followup=208,  (should be 852)
TCGA-44-7662-01A-11D-2063-08 ,       days to last followup=50,   (should be 218)
TCGA-53-A4EZ-01A-12D-A24P-08 ,     days to last followup=280,  (should be 1071)
TCGA-55-8089-01A-11D-2238-08 ,      vital status = Alive ;  days to death=NA,  (should be dead and 702, respectively)
TCGA-73-A9RS-01A-11D-A410-08 ,     vital status = Alive ;  days to death=NA,  (should be dead and 340, respectively)

I also went to "https://portal.gdc.cancer.gov/" to search for these specific cases and confirmed that the pre-compiled TCGAmutations data was inaccurate.

Maybe I'm not processing the clinical data from TCGAmutations correctly:
```
library(TCGAmutations)
library(maftools)
tcga_luad <- tcga_load(study = "LUAD")
luad_maf = read.maf(maf = tcga_luad@data, clinicalData = tcga_luad@clinical.data)
```

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue and for checking the discrepancies. Note that the clinical data I compiled is from almost 7 years ago. It must have been updated significantly. Thanks for pointing to the `clinical_PANCAN_patient_with_followup.tsv` file. I will update the current MAFs and clinical info.

**Comment by mitchellcheung8** [comment]
Hi,

Thank you for your reply. That's what I assumed, that TCGA updated the data.

Concerning your comment that I don't need to use the `read.maf` command, I thought it was useful because it would remove "duplicated variants", that is, variants that map to different transcripts of the same gene?

For example, if I do run the command, I got the following response:
```
> luad_maf = read.maf(maf = tcga_luad@data, clinicalData = tcga_luad@clinical.data)
-Validating
--Removed 12420 duplicated variants
-Summarizing
--Possible FLAGS among top ten genes:
  TTN
  MUC16
  USH2A
-Processing clinical data
-Finished in 4.650s elapsed (4.600s cpu)
```

**Comment by PoisonAlien** [comment]
Hi,

Thanks again for the issue. I have updated the MC3 cohorts along with the clinical data. Please check the README file regarding the survival columns (they are derived from CDR files as per recommendation).

The duplicated variants are due to some tumors being compared to multiple control samples. I have removed duplicated variants in the current update, so you can use it without rereading the MAF.

I hope this helps.

**Comment by PoisonAlien** [comment]
Could you please confirm if this is what the expected output for overall survival?

```r
luad = TCGAmutations::tcga_load(study = "LUAD")
# OS
maftools::mafSurvival(maf = luad, genes = "CDKN2A", time = "CDR_OS.time", Status = "CDR_OS")
```

![](https://github.com/PoisonAlien/TCGAmutations/assets/8164062/4fefc459-45a6-4671-9f2e-9577d67ade7b)

**Comment by mitchellcheung8** [comment]
Hi,

My plot I obtained when manually uploading the 2 TCGA files into R, processing the mutation and clinical text files through 'read.maf', then determining survival with 'mafsurvival',  is very similar to yours (except for small differences in the number of WT samples).  Here is what I got:
![image](https://github.com/PoisonAlien/TCGAmutations/assets/49494692/c73450bd-e3f2-4585-b0e5-3e256c7dac3a)

Here is my code:
```
library(dplyr)

setwd(file.path(Sys.getenv("USERPROFILE"), "Desktop/TCGA/MAF and Copy number/raw data download from GDC/"))

############## Speed everything up by skipping here, and downloading the processed files instead ###################
library(readr) # for importing tsv
# Load MAF and clinical data (files downloaded from  https://gdc.cancer.gov/node/905/ )
All_cancers_mafs<-read_tsv("mc3.v0.2.8.PUBLIC.maf")
All_cancers_clinical<-read_tsv("clinical_PANCAN_patient_with_followup.tsv")

# Subsetting the LUADs (Want the "acronym" column to be "LUAD")
LUAD_subset_clinical <- subset(All_cancers_clinical, grepl("LUAD", acronym))
# rename the bcr_patient_barcode column name to Tumor_Sample_Barcode
colnames(LUAD_subset_clinical)[colnames(LUAD_subset_clinical) == "bcr_patient_barcode"] <- "Tumor_Sample_Barcode"

# Modify All_cancers_mafs$Tumor_Sample_Barcode such that only first eight characters are kept.
All_cancers_mafs$Tumor_Sample_Barcode <- substr(All_cancers_mafs$Tumor_Sample_Barcode, 1, 12)

# Subsetting the MAF for LUAD samples only
# Match Tumor_Sample_Barcode between data and clinical data
matched_LUADsamples <- intersect(LUAD_subset_clinical$Tumor_Sample_Barcode, All_cancers_mafs$Tumor_Sample_Barcode)

# Filter clinical data based on matched samples
LUAD_mafs_text <- All_cancers_mafs[All_cancers_mafs$Tumor_Sample_Barcode %in% matched_LUADsamples, ]

# Cleanup
rm(All_cancers_mafs)
rm(All_cancers_clinical)
rm(matched_LUADsamples)

write_tsv(LUAD_mafs_text, "GDC_LUAD_mafs_text.tsv")
write_tsv(LUAD_subset_clinical, "GDC_LUAD_subset_clinical.tsv")
############## Speed everything up by skipping above, and downloading the processed files instead 


#### Speed things up, Download the processed maf and clinical data (filtered for LUAD)
library(readr) # for importing tsv
LUAD_mafs_text <- read_tsv("GDC_LUAD_mafs_text.tsv")
LUAD_subset_clinical <- read_tsv("GDC_LUAD_subset_clinical.tsv")

library(maftools)
# Converting the maf and clinical text files into a maftools S4 object
luad_maf = read.maf(maf = LUAD_mafs_text, clinicalData = LUAD_subset_clinical)

## Survival based on mutation  
luad_maf_v2 <- luad_maf # Make a copy first

# Create luad_maf_v2@clinical.data$surv_event such that 0 is alive and 1 is dead, 
#     based on $vital_status being Alive or Dead, respectively.
luad_maf_v2@clinical.data$surv_event <- ifelse(luad_maf_v2@clinical.data$vital_status == "Alive", 0, 
                                               ifelse(luad_maf_v2@clinical.data$vital_status == "Dead", 1, NA))

# Create an "overall_survival" variable that is equal to days_to_death for dead patients, 
#         and to days_to_last_follow_up for patients who are still alive
#    Checks each row of luad_maf_v2@clinical.data$surv_event
#         If the value is "1", it fills the corresponding row of luad_maf_v2@clinical.data$overall_survival 
#                   with the value from  "luad_maf_v2@clinical.data$days_to_death"
#         If the value is "0", it fills the corresponding row of luad_maf_v2@clinical.data$overall_survival
#                   with the value from  "luad_maf_v2@clinical.data$days_to_last_followup"
luad_maf_v2@clinical.data$overall_survival <- ifelse(
  luad_maf_v2@clinical.data$surv_event == "1",
  luad_maf_v2@clinical.data$days_to_death,
  luad_maf_v2@clinical.data$days_to_last_followup
)

{genesurvival <- "CDKN2A"
  mafSurvival(
    luad_maf_v2,
    genes = genesurvival,
    samples = NULL,
    clinicalData = NULL,
    time = "overall_survival",
    Status = "surv_event",
    groupNames = c("Mutant","WT"),
    showConfInt = TRUE,
    addInfo = TRUE,
    col = c("maroon", "royalblue"),
    isTCGA = FALSE,
    textSize = 12
  )
}
```


When using the **_website_** to check on the LUAD - CDKN2A mutation status on survival, it was also very similar but not exactly the same:
![image](https://github.com/PoisonAlien/TCGAmutations/assets/49494692/c5f7e294-0711-401e-a7eb-27718824e21c)
When I downloaded the CSV file that is related that this particular survival plot, I counted mutant=20 and Wild-type=486, though the p-value of 0.7971 is still slightly different (I don't think the p-value difference was due to it being a rounded off value and if it was, rounding off 0.7971 would be 0.797 and not 0.798).  Thus, there are tiny differences between the website's survival analysis and our data. Not sure if it is worth analyzing in "microscopic" detail of what caused the small differences and I don't know if there is a wrong or a right.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the detailed reply. Appreciate it. 
Let me know how it goes. If the differences are not too significant, we can ignore them.

**Comment by mitchellcheung8** [comment]
Anand,

Thank you for your reply and insight on the TCGA barcodes.  I'll take a look at your code.  Also, thank you for your work on the various R packages (e.g. maftools, TCGAmutations), as they have been super helpful for my studies!

Best regards,
Mitchell
