### ISSUE TITLE
function getClinicalData() not available

### ISSUE THREAD

**Issue by Aargol** [PoisonAlien/TCGAmutations#2]

**Comment by PoisonAlien** [comment]
getClinicalData is the function `maftools`. You will have to load the maftools library first.

**Comment by Aargol** [comment]
It is available on linux distribution,  while can't load it on Win10 OS :(

**Comment by Aargol** [comment]
On Win10 OS, both getSampleSummary() and getGeneSummary() works well, getClinicalData() not available

**Comment by PoisonAlien** [comment]
Oh, I am guessing you are using an older version of maftools. 
Could you post your sessionInfo ? Or try updating maftools from GitHub or Bioconductor and let me know if you still have the issue.

**Comment by Aargol** [comment]
here is my session info
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1 plyr_1.8.4     Rcpp_0.12.18

**Comment by PoisonAlien** [comment]
Hi,
I need to know the versions of maftools and TCGAMutations packages. Could you load these two package first and post your sessionInfo here.

**Comment by Aargol** [comment]
other attached packages:
[1] maftools_1.2.30     TCGAmutations_0.1.0 Biobase_2.36.2     
[4] BiocGenerics_0.22.1 reshape2_1.4.3

**Comment by PoisonAlien** [comment]
Hi,
Current version of maftools is 1.6.15. 
Please update it and it should work.

**Comment by Aargol** [comment]
yeah, it works perfect. Thanks :D
