### ISSUE TITLE
Clinical data from TCGAmutations to Maftools

### ISSUE THREAD

**Issue by caloto** [PoisonAlien/TCGAmutations#4]
Hello!

I am having some issues in passing samples' clinical data to use it as mentioned in maftools vignettes. I have tried a desperate:

cancer.maf <- toga_acc_mc3
cancer.clinical <- getClinicalData(toga_acc_mc3)

cancer <- read.maf(maf = cancer.maf, clinicalData = cancer.clinical)

and gives an error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'getClinicalData' for signature '"character"'

However, reading the papers for TCGAmutations and Maftools I couldn't figure out how could be possible to connect one with the other.

May you please help me?

Thank you

**Comment by PoisonAlien** [comment]
Hi,
I think you're using way too older of version of `maftools`. 
Could you check your version of maftools ? Current version on Bioconductor is 1.6.15

**Comment by caloto** [comment]
I have that version:

other attached packages:
[1] TCGAmutations_0.2.0 **maftools_1.6.15**     Biobase_2.40.0      BiocGenerics_0.26.0

But I could access doing:

cancer <- read.maf(maf = tcga_cancer_mc3@data, clinicalData = toga_cancer_mc3@clinical.data)

where:
cancer = the name of tumor you are interested on

The whole thing would be:

library(maftools)
library(TCGAmutations)

tcga_load(study = "cancer")

cancer <- read.maf(maf = tcga_cancer_mc3@data, clinicalData = toga_cancer_mc3@clinical.data)

Thank you very much for your time and attention!!! You have done a wonderfull job!

**Comment by PoisonAlien** [comment]
No, You don't have to do the reading part since they are already MAF objects. You can just use them as it is with all the functions from `maftools`. 

Can you try this and see if you get any errors?

```
library("maftools")
TCGAmutations::tcga_load(study = "coad")
maftools::getClinicalData(x = tcga_coad_mc3)
```

**Comment by caloto** [comment]
Thank you very much!  Everything has gone smooth, thank you.

I would like to ask you the last question, where can i get gistic data to use in maftools as in the example case of LAML??

**Comment by PoisonAlien** [comment]
I usually download them from TCGA firehose with `firehose_get` utility. Check [here](https://confluence.broadinstitute.org/display/GDAC/Download)

**Comment by caloto** [comment]
Thank you very much!!

Congrats for the tool, it is really powerful!

**Comment by PoisonAlien** [comment]
I am glad that you find the tool useful. 
I am closing this issue for now. Please feel free to re-open if necessary.
