### ISSUE TITLE
Downloading mc3.v0.2.8.PUBLIC.maf

### ISSUE THREAD

**Issue by crasper9** [PoisonAlien/TCGAmutations#5]
So I am new to R, new to Github, new to coding... I apologize for simple minded questions. I am trying to generate a gene expression analysis heatmap using 10 genes (10 genes). I basically want to see the number of mutations in these genes in each of the TCGA cancers. I was directed to install the maf file from the https://gdc.cancer.gov/about-data/publications/mc3-2017 website. I am also using a Mac. So I downloaded the file "mc3.v0.2.8.PUBLIC.maf" and everytime I download it, I open to see how big the file is and its only 66KB on disk! Would you be able to help me?

**Comment by PoisonAlien** [comment]
Hi,
You can download it from [here](https://api.gdc.cancer.gov/data/1c8cfe5f-e52d-41ba-94da-f15ea1337efc) 
Its around 170+ mb compressed file.

**Comment by crasper9** [comment]
Just figured out the problem. For some reason Safari wasn't properly downloading the file. Everytime I downloaded it the file only appeared to have 66KB, and idk why. So I tried a different browser, Chrome, and it worked.

Thank you
