### ISSUE TITLE
TGCA visualisation in lolliplots

### ISSUE THREAD

**Issue by IrisSWE** [PoisonAlien/TCGAmutations#6]
Hi, thank you so much for all your powerful tools!

I was thinking to compare my data with the tcga precompiled mafs in terms of visualizing the mutations on certain genes (aka lolliplots for two maf files). Problem is that due to space there is no protein change or AA change column.  And when I use the HGVSp_Short I get an error (Error in subsetMaf(maf = maf, includeSyn = FALSE, genes = geneID, query = "Variant_Type != 'CNV'") : 
  trying to get slot "maf.silent" from an object (class "data.table") that is not an S4 object ).

Do you think there is a faster way to do that through maftools? 
Was thinking to annotate the maf but it doesn't really work...I also tried to extract only chr, start, end and make a new maf for the genes that I want ...so that is why I am reaching out to you in case you have a "quicker" way to do this.

best
Iris

**Comment by PoisonAlien** [comment]
Hi,
If I understand your question correctly, you have an maf-like file with no protein change information and you want to compare it to tcga cohort?
Without protein change info it is not possible to draw lollipop plots.

**Comment by IrisSWE** [comment]
Hi, 
thanks for your quick reply!
yes, I have a maf that I have already analyzed in various ways. When I visualize my mutations (lolliplots) I want to contrast them with the known mutations from tcga and I am using the HGVSp_Short column ( HGVSp_Short =  p.S183* ). for that(lolliplot2). It doeasn't really work if I subset the tcga maf for the genes that I want to look at. 

best 
Iris

**Comment by PoisonAlien** [comment]
okay, when you subset the maf, set the argument `mafObj = TRUE` and use it for lollipopPlot2. Let me know if this fixes the problem.

**Comment by IrisSWE** [comment]
Hi again, 
worked like a charm!
I also saw that there is no "repel"  or "collapsePosLabel" in lolliplot2, it would be nice to have them :D 
10000 thanks.
