### ISSUE TITLE
Error: object 'tcga_laml_mc3' not found

### ISSUE THREAD

**Issue by jdjdj0202** [PoisonAlien/TCGAmutations#9]
Hi. 
I have a following error message.
Error: object 'tcga_laml_mc3' not found

Do I need to download tcga_laml_mc3 file from somewhere? 

Thanks.

**Comment by PoisonAlien** [comment]
Hi,
It seems to work on my system. Could you please post your sessionInfo and commands used?

**Comment by jdjdj0202** [comment]
Hi! Thank you for your reply. 
Actually, I did not use totally same as your codes but I think the code lead to the error was the same. 
I've got the commands from one of my friends. 
I used the commands as follows.

============================================================
if (!requireNamespace("BiocManager", quietly=TRUE))
  install.packages("BiocManager")
BiocManager::install("maftools")
BiocManager::install("Matrix")
BiocManager::install("Purrr")
BiocManager::install("ggplot2")
BiocManager::install("devtools")
devtools::install_github(repo="PoisonAlien/TCGAmutations")

library(devtools)
library(TCGAmutations)
library(maftools)
library(Matrix)
library(purrr)
library(dplyr)
library(ggplot2)

TCGAmutations::tcga_available()

TCGAmutations::tcga_load(study="LAML")
tcga_laml_mc3


I am a beginner and not familiar with R errors. 
I'd really appreciate it if you could give some advice. 
Thank you so much!

**Comment by PoisonAlien** [comment]
You're almost there. `tcga_load` function returns an MAF object rather than loading it into environment. You just need to assign it to a variable.

```r
laml = TCGAmutations::tcga_load(study="LAML")
```

**Comment by jdjdj0202** [comment]
It works. Thank you so much!!!  :-)
